[project]
name = "lib-ml"
version = "0.1.0"
description = "Text cleaning & tokenization for sentiment analysis"
requires-python = ">=3.8"

dependencies = [
  "nltk>=3.7,<4.0",
  "scikit-learn>=1.1,<2.0",
]
