name: Pre-release

on:
  release:
    types: [published]

jobs:
  create_prerelease:
    if: "!contains(github.event.release.tag_name, '-pre')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Calculate next pre-release version
        id: calc_version
        run: |
          BASE_VERSION=${{ github.event.release.tag_name }}
          BASE_VERSION=${BASE_VERSION#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$BASE_VERSION"
          PATCH=$((PATCH + 1))
          PRE_RELEASE_TAG="v${MAJOR}.${MINOR}.${PATCH}-pre"
          echo "pre_release_tag=$PRE_RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Next pre-release tag: $PRE_RELEASE_TAG"

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.calc_version.outputs.pre_release_tag }}
          name: "Pre-release ${{ steps.calc_version.outputs.pre_release_tag }}"
          body: |
            Automated pre-release based on ${{ github.event.release.tag_name }}.

            This is a pre-release for testing purposes.
          prerelease: true
          draft: false
