name: Release lib-ml
on:
  push:
    tags:
      - '*.*.*'

env:
  PACKAGE_NAME: lib-ml
  OWNER: remla25-team7

permissions:
  contents: read
  packages: write   

jobs:
  details:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.extract.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: extract
        name: Extract version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VER=$(echo "$TAG" | cut -d'-' -f1)
          echo "new_version=$VER" >>"$GITHUB_OUTPUT"

  build:
    needs: details
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build tool
        run: pip install --upgrade build

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload \
            --repository-url https://upload.pypi.pkg.github.com/${{ env.OWNER }} \
            dist/*