#
name: Publish lib‑ml to GitHub Packages

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}          # strip leading refs/tags/v
          MAJOR=$(cut -d. -f1 <<<"$VERSION")
          MINOR=$(cut -d. -f2 <<<"$VERSION")
          PATCH=$(cut -d. -f3 <<<"$VERSION")
          echo "VERSION=$VERSION"           >> $GITHUB_ENV
          echo "VERSION_MAJOR=$MAJOR"       >> $GITHUB_ENV
          echo "VERSION_MINOR=$MINOR"       >> $GITHUB_ENV
          echo "VERSION_PATCH=$PATCH"       >> $GITHUB_ENV

      - name: Sync version.py with tag
        run: |
          echo "__version__ = \"${VERSION}\"" > lib_ml/version.py

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build distributions
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload \
            --repository-url https://upload.pypi.pkg.github.com/${{ github.repository_owner }} \
            dist/*
