name: Stable Release lib-ml

on:
  push:
    # Only on tags like v1.2.3
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write     # for pushing commits & tags
  packages: write     # for publishing to GitHub Packages

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      # The full ref name, e.g. "v1.2.3"
      TAG_REF: ${{ github.ref_name }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        id: extract_version
        run: |
          # strip leading "v" → "1.2.3"
          VER=${TAG_REF#v}
          echo "VER=$VER" >> $GITHUB_ENV
          # expose for body
          echo "PKG_VERSION=$VER" >> $GITHUB_OUTPUT

      - name: Sync lib_ml/version.py
        run: |
          echo "__version__ = '$VER'" > lib_ml/version.py

      - name: Set up Python & build
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build package
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          python setup.py sdist bdist_wheel

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Python package **lib-ml** version **${{ steps.extract_version.outputs.PKG_VERSION }}** published!

            Install with:

            ```bash
            pip install --extra-index-url https://pkg.github.com/${{ github.repository_owner }} lib-ml==${{ steps.extract_version.outputs.PKG_VERSION }}
            ```
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump to next pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # X.Y.Z → X.Y.(Z+1)-pre.1
          IFS='.' read MAJ MIN PATCH <<< "$VER"
          NEXT_PATCH=$((PATCH + 1))
          NEW="${MAJ}.${MIN}.${NEXT_PATCH}-pre.1"

          echo "__version__ = '$NEW'" > lib_ml/version.py
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lib_ml/version.py
          git commit -m "chore: bump to $NEW"
          git push 

          git tag "v$NEW"
          git push origin "v$NEW"
